### ISSUE TITLE
cooklang-parser on the linux command line

### ISSUE THREAD

**Issue by Lonerider2010** [biowaffeln/cooklang-parser#1]
Hello @biowaffeln,
I would like to use your cooklang-parser on the linux command line. How can I achieve that?
Thanks for your support and best regards.

**Comment by biowaffeln** [comment]
Hi! This project is just a couple of TypeScript files, you can use the code in Node.js and create a CLI app with it. I haven't published it on npm yet... for now you'd have to copy-paste it.
What's the use-case you have in mind? If you just want to organise your recipes, generate shopping lists, etc. you can use the official cooklang CLI for that: https://github.com/cooklang/CookCLI

**Comment by Lonerider2010** [comment]
Hello @biowaffeln,
thank you for the prompt answer. Yes, I know about CookCLI and am actually using it. Now I would like to convert my recipes to HTML in order to build a cookbook from them, for example with wkhtmltopdf.
One option would be the Obsidian extension [CookLang Editor](https://github.com/deathau/cooklang-obsidian), which actually generates an HTML code, but only for the Obsidian preview.
So I found your cooklang-parser, which does exactly what I need, but I am not firm with node.js and TypeScript. So please tell me the four or more steps that are necessary to create a CLI app from it.
Thanks in advance.

**Comment by biowaffeln** [comment]
Alright, so I went ahead and published the package on npm so it's easier to get started: https://www.npmjs.com/package/cooklang-parser

Here's a good blog post for how to get started with Node.js CLIs:
https://developer.okta.com/blog/2019/06/18/command-line-app-with-nodejs

What `cooklang-parser` does is take a recipe and return an object containing the recipe information (if you go to the [demo](https://biowaffeln.github.io/cooklang-parser/) and click on "AST", you'll see what it looks like). So essentially what you have to do is: 
1. read the recipe from the file system
2. parse it with `cooklang-parser`
3. generate HTML from the parsed result 
4. write the HTML to the disc

Here's how I generate the markup in my demo, might be useful as a reference (I'm using React): https://github.com/biowaffeln/cooklang-parser/blob/main/demo/src/components/RecipeRenderer.tsx#L42

Hope that helps, let me know if you have any questions!

**Comment by Lonerider2010** [comment]
@biowaffeln, thanks for these instructions. Now I managed to learn that much of JavaScript and node.js, that I could set up a program which executes step 1 and 2. Also I am sure that I will be able to realize step 4. But with step 3, I cannot find a way to integrate your RecipeRenderer. As I find the output generated by this renderer very good, and do not want to reinvent the wheel, I would appreciate to learn from you, how to use it in my JavaScript program. Can you help me there?

**Comment by biowaffeln** [comment]
Ok so what you want to do is go over the steps/ingredients/cookware-array and concatenate them together into a single string. One way you could do that is with a couple of for loops, here's an example for how you could do it for the steps:

```js
function generateSteps(recipe) {
  let content = ""
  
  for (let step of recipe.steps) {
    // we put each step into its own p tag
    content += `<p class="step">`
    
    // we put each token inside a step into its own span tag
    for (let token of step) {
      if(token.type === "text")
        content += `<span class="text">${token.value}</span>`
      if(token.type === "ingredient")
        content += `<span class="ingredient">${token.name}</span>`
      // ...
    }
    
    // don't forget to close the tag!
    content += "</p>"
  }
  
  return content;
}

const html = `<html>
  <head>
    <title>${recipe.metadata.title}</title>
  </head>
  <body>${generateSteps(recipe)}</body>
</html>
`
```

The code for the ingredients, cookware, etc. would look very similar.

**Comment by Lonerider2010** [comment]
@biowaffeln, thanks for these hints. This works for metadata, ingredients, and cookware. But especially for steps it does not work. The output of the cooklang-parser for steps looks like this:
```
steps: [
    [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object]
    ],
    [ [Object], [Object], [Object], [Object], [Object], [Object] ],
    [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ],
    [ [Object] ],
    [ [Object], [Object] ],
    [ [Object], [Object] ],
    [ [Object], [Object], [Object], [Object], [Object] ]
  ]
```
So I don't know how to handle this.

The other question is: is there no way to make the RecipeRenderer a CLI app? That would shorten the way to get recipes in HTML format a lot.

**Comment by biowaffeln** [comment]
Ohh I just realised I had a typo in my original code 😅 mixed up "token" and "step" in that inner for loop...
Anyway, here's a working example: https://replit.com/@biowaffeln/cooklang2html

I think this is more of a "do one thing well" type of library, having a CLI app that generates HTML is out of scope. But if you finish your CLI app you should create a repository for it! Might be useful for other people.

I'm closing this issue now since it's not really pertinent to this repo. If you have any questions related to your project I'm happy to chat, just send me an e-mail or DM me on twitter.
